import type { CSSProperties } from 'react';

type CompanyIconProps = {
  type: string;
  className?: string;
  style?: CSSProperties;
};

export function CompanyIcon({ type, className = '', style }: CompanyIconProps) {
  return <i className={`iconfont ${type} company-icon ${className}`.trim()} style={style} aria-hidden="true" />;
}

export const companyIcons = {
  add: 'icon-jia',
  aiAgent: 'icon-a-zhinengtizhinengtizhinengshitizhinengdailizhinengtixitongzhinengtichengxuzhinengtiruanjianzizhuzhinengtizhinengzhutizhinengti',
  aiChat: 'icon-a-AIduihuaAIjiaotanrengongzhinengduihuaAIduihuajiaohurengongzhinengjiaotanAIliaotianrengongzhinengliaotianAIduihuagoutong',
  aiOverview: 'icon-a-gailanAI',
  appFramework: 'icon-webyingyongkuangjia',
  applicationInfo: 'icon-webyingyongxinxi',
  attachment: 'icon-fujian',
  alertLevel: 'icon-a-biaoqianjingbaojingshibaojing',
  authorization: 'icon-shouquanguanli',
  center: 'icon-duojizhongxin',
  collapse: 'icon-xiangzuozhankai',
  component: 'icon-zujianxinxi',
  confirm: 'icon-dui',
  copy: 'icon-fuzhi',
  close: 'icon-guanbigaoliang',
  closeCircle: 'icon-a-cuoguanbi',
  download: 'icon-xiazai',
  deepThink: 'icon-a-shendusikaoshendusisuoshenrusikaoshencengsikaoshendukaoliangshendusilvshenrusisuoshencengsisuoshenduzhuomoshenruzhuomo',
  down: 'icon-xiajiantou',
  edit: 'icon-bianji',
  expand: 'icon-xiajiantou',
  export: 'icon-a-daochutiaozhuan',
  filter: 'icon-shaixuan',
  failed: 'icon-a-cuowushibai',
  fullscreen: 'icon-quanping',
  knowledgeBase: 'icon-a-zhishikuzhishichubeikuxinxiziliaokuzhishijihexinxijihekuzhishicangkuxinxicangchuzhishidangankuxinxidanganzhishi',
  highConfidence: 'icon-gaozhixin',
  ignore: 'icon-hulve',
  inProgress: 'icon-lishijilu',
  lowConfidence: 'icon-dizhixin',
  maintenanceOrganization: 'icon-weihuzuzhi',
  menu: 'icon-caidan',
  message: 'icon-a-tixinglingdang',
  mute: 'icon-guanbishengyin',
  mediumConfidence: 'icon-zhongzhixin',
  product: 'icon-gongyechanpin',
  play: 'icon-bofang',
  refresh: 'icon-a-shuaxingengxinzhongzhi',
  riskAsset: 'icon-a-kehuduandiannao',
  sdk: 'icon-SDKwenjian',
  search: 'icon-a-sousuofangdajing',
  search360: 'icon-a-360qiyezhinao',
  screenshot: 'icon-jieping',
  send: 'icon-a-fasongfabufeiji',
  securityCenter: 'icon-anquanzhongxin',
  securityEvent: 'icon-gaojing',
  securityPolicy: 'icon-anquanpeizhi',
  setting: 'icon-a-shezhixitong',
  success: 'icon-a-tongguochenggong',
  stop: 'icon-tingzhi',
  task: 'icon-a-renwushiminggongzuozhizechashizhuananxiangmurenwuxiangshimingzhifenshiwuweipaizhutuozechengdandangshimingren',
  terminal: 'icon-zhongduanfuwuqi',
  terminalOnline: 'icon-zhongduanfuwuqi1',
  time: 'icon-a-shijianriqizhongbiao',
  trendDown: 'icon-xiajiang',
  trendUp: 'icon-shangsheng',
  threatLevel: 'icon-eyilanjie',
  thumbsDown: 'icon-buxihuan',
  thumbsUp: 'icon-dianzan',
  upload: 'icon-shangchuan',
  uploadImage: 'icon-tupian1',
  user: 'icon-a-yonghuzhanghaoguanliyuan',
  visualization: 'icon-keshihua',
  voice: 'icon-maikefeng',
  volume: 'icon-kaiqishengyin',
  vulnerability: 'icon-loudong',
  waiting: 'icon-shalou',
  warning: 'icon-a-zhuyitishi',
  webSearch: 'icon-wangluo',
  visible: 'icon-a-kejianyanjing',
  hidden: 'icon-a-bukejianbiyan',
  help: 'icon-a-tishibangzhu',
};
